source 'https://github.com/CocoaPods/Specs.git'

target 'CGLDefaultsBackedPropertyObserver', :exclusive => true do
  pod "CGLDefaultsBackedPropertyObserver", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CGLDefaultsBackedPropertyObserver", :path => "../"

  
end
